[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.3.0"

[[constraint]]
  name = "github.com/dimfeld/httptreemux"
  version = "5.0.2"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "4.0.1"

[[constraint]]
  name = "github.com/devopsfaith/flatmap"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
